### ISSUE TITLE
Add optional `channal` param to ZeroPush.register

### ISSUE THREAD

**Issue by snatchev** [ZeroPush/zero_push#1]
moving issue from: https://github.com/SymmetricInfinity/zero_push/issues/7

**Comment by ACPK** [comment]
Any status on this?

**Comment by snatchev** [comment]
@ACPK This feature is present in the gem. The issue should have been closed a while ago, sorry for the confusion.
https://github.com/ZeroPush/zero_push/blob/master/lib/zero_push/client.rb#L71
