### ISSUE TITLE
Please extract Zeropush endpoint url into attribute 

### ISSUE THREAD

**Issue by FallDi** [ZeroPush/zero_push#11]
https://github.com/ZeroPush/zero_push/blob/master/lib/zero_push/client.rb

Can you make this parameterized?
    URL = 'https://api.zeropush.com'.freeze
It helps customers who migrated to another services

**Comment by sprad** [comment]
Hi @FallDi .  I think your solution is technically superior because it allows for more flexibility, but for those looking to migrate to PushWoosh they can checkout an updated (and renamed) version of this gem to use with PushWoosh:

https://github.com/cortexintel/zero_push_woosh

**Comment by FallDi** [comment]
Nice work! Tnx
