### ISSUE TITLE
Add a nice way to manage multiple Apps.

### ISSUE THREAD

**Issue by snatchev** [ZeroPush/zero_push#4]
ZeroPush gives you a pair of tokens for each app. It would be nice to have an easy way to configure an switch to which app you want to send requests.

**Comment by snatchev** [comment]
@simonprev thanks for the suggestion! I've added a similar, and somewhat simpler way to instantiate clients based on their auth_token hash key like this:
```ruby
ZeroPush.auth_tokens = { apns_dev: "abc", apns_prod: "def", gcm_dev: "xyz" }
ZeroPush.apns_dev.verify_credentials
ZeroPush.gcm_dev.verify_credentials
```

**Comment by simonprev** [comment]
Yeah I like your version better too :smile:

Thanks for implementing this!
